# Generated by Django 4.2.20 on 2025-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_user_chat_id_user_unique_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_token',
            field=models.CharField(blank=True, max_length=33, null=True, unique=True),
        ),
    ]
