name: Deploy MemHub

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.env' \
            --exclude 'venv' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ root@109.68.215.67:/srv/MemHub/

      - name: Restart containers
        run: |
          ssh -o StrictHostKeyChecking=no root@109.68.215.67 "
            cd /srv/MemHub
            docker-compose down
            docker-compose up --build -d
          "