name: Deploy MemHub to Production

on:
  push:
    branches: [ main ]  # Или master, если используете эту ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to server
      run: |
        rsync -avz --delete \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='media/' \  # Исключаем media, если используете Docker volumes
          -e ssh ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/MemHub/

    - name: Rebuild and restart containers
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /srv/MemHub
        docker-compose down
        docker-compose pull
        docker-compose build --no-cache
        docker-compose up -d
        EOF